In [107]:
import numpy as np

**1.** Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [108]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

**2.** Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [109]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)

In [110]:
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [111]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [112]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [113]:
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [114]:
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

**3.** Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [115]:
a1_1 = a.reshape(2, -1)
a2_1 = a.reshape(3, -1)
a3_1 = a.reshape(4, -1)
a4_1 = a.reshape(-1, 2)
a5_1 = a.reshape(-1, 1)

In [116]:
a1_1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [117]:
a2_1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [118]:
a3_1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [119]:
a4_1

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [120]:
a5_1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

**4.** Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Ответ: с точки зрения NumPy - нет.

**5.** Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [121]:
arr = np.random.randn(3, 4)
arr

array([[ 0.0675282 , -1.42474819, -0.54438272,  0.11092259],
       [-1.15099358,  0.37569802, -0.60063869, -0.29169375],
       [-0.60170661,  1.85227818, -0.01349722, -1.05771093]])

In [122]:
arr.size

12

In [123]:
arr_1 = arr.reshape(12)
arr_1

array([ 0.0675282 , -1.42474819, -0.54438272,  0.11092259, -1.15099358,
        0.37569802, -0.60063869, -0.29169375, -0.60170661,  1.85227818,
       -0.01349722, -1.05771093])

In [124]:
arr_1.size

12

In [125]:
arr_1.size == arr.size

True

**6.** Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [126]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [127]:
a.ndim

1

**7.** Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами

In [128]:
b = np.arange(20, 1, -2).reshape(10, 1)
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

In [129]:
b.ndim

2

b является двумерным.

**8.** Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [130]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [131]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [132]:
v = np.concatenate((a, b), axis=0)
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [133]:
v.size

10

In [134]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [135]:
v.size

10

**9.** Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [136]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [137]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [138]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [139]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [140]:
d = np.linalg.det(B)
d

0.0

Ответ: Нет. Т.к. определитель равен нулю.

**10.** Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [141]:
np.random.seed(42)
np.random.rand(10)


array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

**11.** Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [142]:
C = np.random.randint(0, 16, size = 16)
C

array([ 5,  4,  1,  7, 11, 13,  5,  1, 15, 11,  4,  0, 11,  9,  5, 12])

**12.** Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [143]:
C.resize(4, 4)
C

array([[ 5,  4,  1,  7],
       [11, 13,  5,  1],
       [15, 11,  4,  0],
       [11,  9,  5, 12]])

In [144]:
D = (C * 10) + B
D

array([[ 55,  54,  33, 102],
       [124, 180, 136, 132],
       [173, 196, 189, 212],
       [142, 212, 262, 422]])

In [145]:
determ  = np.linalg.det(D)
determ

72557599.99999987

In [146]:
r = np.linalg.matrix_rank(D)
r

4

In [147]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00980683, -0.01670645,  0.02091966, -0.00765406],
       [ 0.00539875,  0.02483241, -0.02053706,  0.0012448 ],
       [-0.02579633, -0.00913233,  0.01239567,  0.00286448],
       [ 0.01000364, -0.00118361, -0.00441801,  0.00254143]])

In [148]:
D.dot(D_inv)

array([[ 1.00000000e+00, -4.16333634e-17, -2.77555756e-16,
         1.66533454e-16],
       [-6.66133815e-16,  1.00000000e+00,  1.11022302e-16,
         1.11022302e-16],
       [ 0.00000000e+00,  4.44089210e-16,  1.00000000e+00,
         1.11022302e-16],
       [-8.88178420e-16,  2.22044605e-16, -4.44089210e-16,
         1.00000000e+00]])

**13.** Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [149]:
D_inv[D_inv > 0] = 1
D_inv

array([[ 1.        , -0.01670645,  1.        , -0.00765406],
       [ 1.        ,  1.        , -0.02053706,  1.        ],
       [-0.02579633, -0.00913233,  1.        ,  1.        ],
       [ 1.        , -0.00118361, -0.00441801,  1.        ]])

In [150]:
D_inv[D_inv < 0] = 0

In [151]:
D_inv

array([[1., 0., 1., 0.],
       [1., 1., 0., 1.],
       [0., 0., 1., 1.],
       [1., 0., 0., 1.]])

In [152]:
C

array([[ 5,  4,  1,  7],
       [11, 13,  5,  1],
       [15, 11,  4,  0],
       [11,  9,  5, 12]])

In [153]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [154]:
E = np.where(D_inv == 1, B, C)
E

array([[  5,   4,  23,   7],
       [ 14,  50,   5, 122],
       [ 15,  11, 149, 212],
       [ 32,   9,   5, 302]])